import { BillingReport } from './types';

export async function sendBillingReport(
  apiKey: string,
  to: string,
  report: BillingReport
) {
  const html = generateHtml(report);

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Billing Reporter <onboarding@resend.dev>', // Update this if you have a custom domain verified in Resend
      to: [to],
      subject: `Weekly Billing Report - ${new Date().toLocaleDateString()}`,
      html: html,
    }),
  });

  if (!response.ok) {
    throw new Error(`Failed to send email: ${response.statusText}`);
  }
}

function generateHtml(report: BillingReport): string {
  const { vercel, cloudflare, google } = report;
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        h1 { color: #111; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        h2 { color: #444; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { text-align: left; padding: 8px; border-bottom: 1px solid #eee; }
        th { background-color: #f9f9f9; }
        .total { font-weight: bold; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Weekly Billing Summary</h1>
        <p>Report for the last 7 days.</p>

        <h2>▲ Vercel</h2>
        <table>
          <tr><th>Metric</th><th>Usage</th></tr>
          <tr><td>Bandwidth</td><td>${vercel.bandwidth} GB</td></tr>
          <tr><td>Function Invocations</td><td>${vercel.functionInvocations.toLocaleString()}</td></tr>
          <tr><td>Build Minutes</td><td>${vercel.buildMinutes}</td></tr>
        </table>

        <h2>☁️ Cloudflare (R2)</h2>
        <table>
          <tr><th>Metric</th><th>Usage</th></tr>
          <tr><td>Storage Used</td><td>${cloudflare.storageUsed} GB</td></tr>
          <tr><td>Class A Ops</td><td>${cloudflare.classAOperations.toLocaleString()}</td></tr>
          <tr><td>Class B Ops</td><td>${cloudflare.classBOperations.toLocaleString()}</td></tr>
        </table>

        <h2>🧠 Google (Gemini)</h2>
        <table>
          <tr><th>Service</th><th>Usage / Cost</th></tr>
          ${google.services.map(s => `<tr><td>${s.name}</td><td>${s.cost.toLocaleString()}</td></tr>`).join('')}
        </table>
        
        <p style="margin-top: 40px; color: #666; font-size: 12px;">
          Generated by Billing Worker at ${new Date(report.timestamp).toLocaleString()}
        </p>
      </div>
    </body>
    </html>
  `;
}

